var express = require('express');
var router = express.Router();


router.get('/', function(req, res, next) {

    const data = [
        ['ID', 'Term', 'Description', 'References'],
        ['1', 'waterfall methodology', ' linear approach to project management that requires each phase to be completed before moving on to the next', '[1]E. Corrales, “SDLC: What Is The Waterfall Model?,” Developer.com, Jun. 10, 2022. https://www.developer.com/project-management/sdlc-waterfall-model/'],
        ['2', 'Shift-left testing', 'testing software early in the development process', '[2]“Shift-left testing,” Wikipedia, Jun. 30, 2022. https://en.wikipedia.org/wiki/Shift-left_testing'],
        ['3', 'Agile', 'a type of software development methodology that focuses on the early delivery, continual improvement, and encourages flexible responses to change', '[3]H. Baashen, “Agile Methodology,” Medium, Jan. 26, 2021. https://blog.devgenius.io/agile-methodology-c9745645b4d'],
        ['4', 'DevOps', 'a software development approach that combines development (Dev) and operations (Ops) teams to enhance collaboration, automate processes, and deliver software more efficiently.', '[4] OpenAI. "what is DevOps? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['5', 'production environment', 'operational environment where a software application or system is deployed and made available for end-users', '[5] OpenAI. "what is production environment in IT industry? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['6', 'ITSM automation', 'the use of tools, technologies, and practices to automate and streamline various aspects of IT service management (ITSM) processes. ', '[6] OpenAI. "what is ITSM automation in IT industry? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['7', 'Scrum', 'an agile project management system commonly used in software development', '[7]Wikipedia Contributors, “Scrum (software development),” Wikipedia, Apr. 16, 2019. https://en.wikipedia.org/wiki/Scrum_(software_development)'],
        ['8', 'Microservices', 'an architectural approach where a complex software application is broken down into smaller, independent, and loosely coupled services. Each service focuses on a specific business capability and can be developed, deployed, and scaled independently.', '[8] OpenAI. "what is Microservices in IT industry? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['9', 'Deployment Pipeline', 'an automated sequence of steps or stages that software goes through from development to production. It is a continuous delivery mechanism that allows for the efficient and controlled release of software.', '[9] OpenAI. "what is Deployment Pipeline in IT industry? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['10', 'Continuous Integration', 'a software development practice where developers frequently integrate their code changes into a shared repository. Each integration triggers an automated build process that compiles the code, runs automated tests, and detects integration issues or conflicts.', '[10] OpenAI. "what is Continuous Integration in IT industry? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['11', 'Infrastructure as a Code', 'Infrastructure as Code (IaC) is the process of managing and provisioning infrastructure through code instead of through manual processes 1. It uses DevOps methodology and versioning with a descriptive model to define and deploy infrastructure, such as networks, virtual machines, load balancers, and connection topologies 2. With IaC, configuration files are created that contain your infrastructure specifications, which makes it easier to edit and distribute configurations. It also ensures that you provision the same environment every time 1.', '[11] OpenAI. "what is Infrastructure as a Code? please give me a concise definition" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['12','Site reliability engineering (SRE)','similar to DevOps engineering but focus more on reliability, aiming to improve latency, availability. etc. ','“Site reliability engineering,” Wikipedia, Oct. 22, 2021. https://en.wikipedia.org/wiki/Site_reliability_engineering'],
        ['13','definition of done','the fact that all condition and acceptance criteria regarding the software product are satisfied and ready to be used by end users. The one cannot meet the definition is considered as poor quality','D. HUETHER, "The Definition of Done," LeadingAgile, Feb. 08, 2017. https://www.leadingagile.com/2017/02/definition-of-done/'],
        ['14','deliverables','items can be used for target users, which indicates work completed. It also implied the end of the project process','“What is a Deliverable in Project Management?,” Wrike, 2022. https://www.wrike.com/project-management-guide/faq/what-is-a-deliverable-in-project-management/'],
        ['15','Regression test','the practise that re-running Functional and technical tests to ensure that any modifications to the software code during the development cycle had not caused any problems.','J. Mulder, Enterprise DevOps for Architects. Packt Publishing Ltd, 2021.'],
        ['16','End-to-end responsibility','a requirement that teams must take responsibility from the start to the finish of the project. ','J. Mulder, Enterprise DevOps for Architects. Packt Publishing Ltd, 2021.'],
        ['17','Cross-functional autonomous teams ','refers to a team whose memebers come from various disciplines and functional areas','OpenAI. "what is the term "Cross-functional autonomous teams" in DevOps field?" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['18','Portfolio and configuration management','building blocks which is reusable, replaceable and clearly defined. It is under configuration management and can be automated','J. Mulder, Enterprise DevOps for Architects. Packt Publishing Ltd, 2021.'],
        ['19','behaviour-driven design (BDD)','a methodology to improve the understanding of requirements and make sure software development is driven by desired behaviours defined by business perspective','OpenAI. "what is the term "behaviour-driven design (BDD)" in DevOps field?" OpenAI ChatGPT, 2023, chat.openai.com.'],
        ['20','test-driven development (TDD)','a practice that programmers write unit test cases before writing concrete code to implement the concept of continuous test and improvement','OpenAI. "what is the term "test-driven development (TDD)" in DevOps field?" OpenAI ChatGPT, 2023, chat.openai.com.']
    ];

    res.render('index', { data });
});

module.exports = router;